function Hd = eeg_noth_f(fs,notch_f)
%EEG_NOTH_F 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 12-Sep-2025 15:07:22

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

Fnotch = notch_f;  % Notch Frequency
BW     = 5;   % Bandwidth
Apass  = 2;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
