function Hd = emg_comb_f(fs)
%EMG_COMB_FILTER 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 12-Sep-2025 09:27:24

% IIR Comb Notching filter designed using the IIRCOMB function.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N     = fs/50;  % Order
BW    = 5;   % Bandwidth
Apass = 2;   % Bandwidth Attenuation

[b, a] = iircomb(N, BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% Hd.a = a;
% Hd.b = b;

% [EOF]
