function Hd = emg_hp_f(fs,fc)
%UNTITLED 返回离散时间滤波器对象。

% MATLAB Code
% Generated by MATLAB(R) 23.2 and DSP System Toolbox 23.2.
% Generated on: 12-Sep-2025 10:14:58

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
Fs = fs;  % Sampling Frequency

N  = 4;   % Order
Fc = fc;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% 获取传递函数值。
[b, a] = tf(Hd);

% 转换为单一滤波器。
Hd = dfilt.df2(b, a);

% [EOF]
